#! /bin/bash

# Set here the application root path
export HIWEFAI_ROOT=/projects/HiWeFAI/apps/hiwefai

###############################################################################
## Models                                                                    ##
###############################################################################

